### ISSUE TITLE
The project imports can't be resolved

### ISSUE THREAD

**Issue by bmihovski** [imbacraft/dusk.nvim#13]
I faced an issue where when a java file is open the the project imports can't be resolved. 
The workaround is to wipe the project data and restart the server at every time when  nvim is re opened.

My feeling is the server is doing some clean up at start time and this messing up the project

The errors are like this              └──── 268435846: The import com.my.project.entities cannot be resolved

**Comment by imbacraft** [comment]
Thanks for the input. I haven't touched the JDTLS settings for some time. I think this might be related to the build tool you're using. Can you share more details on what build tool you're using and what's your pom.xml or build.gradle?

**Comment by imbacraft** [comment]
@bmihovski Latest commit on master disables root_dir detection for sonarlint (wasn't working correctly anyway). Try to see if that helps with your issue. That root_dir config might have called jdtls setup too early.

**Comment by bmihovski** [comment]
Thank you for your help! It's a gradle. Unfortunately, can't upload it since is a the project where I'm working.
However, I can check for specific gradle definition if you point me what do we need from there.
It's a pity because yesterday was fine with the old dusk config. I will try to revert their repo

Here  a picture from the project deletion at start. I'm wondering why jdtls needs to delete it (the project name is reprocessing) 

![image](https://github.com/imbacraft/dusk.nvim/assets/4339683/760afdaf-b87b-4f4b-b62a-32e7f5e35b5c)

**Comment by imbacraft** [comment]
What java version is the project using? What version of gradle? Are they compatible with each other? JDTLS deletes the project folder because it rebuilds it every time. That's expected behavior.

Also, have you tried updating the project config (space + j + u) and re-compiling (space + j + C) ? They might save you some restarts.

**Comment by bmihovski** [comment]
java 21 gradle is compatible the project is working with intellij Here is the build gradle But look it seems to be a project specific we have workaround so maybe we can ignore it for now

here some errors from the logs

16:00:07] ...lsp/handlers.lua:623	"Jun 1, 2024, 4:00:07 PM Command _java.reloadBundles.command not supported on client"
[ERROR][2024-06-01 16:00:07] ...lsp/handlers.lua:623	"Jun 1, 2024, 4:00:07 PM Failed to add classpath entry for generated source folder annotations\nCannot nest 'reprocessing/bin/generated-sources/annotations' inside output folder 'reprocessing/bin'\nJava Model Exception: Error in Java Model (code 964): Cannot nest 'reprocessing/bin/generated-sources/annotations' inside output folder 'reprocessing/bin'\n\tat org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:801)\n\tat org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3518)\n\tat org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3478)\n\tat org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3534)\n\tat org.eclipse.jdt.apt.core.internal.generatedfile.ClasspathUtil.updateProjectClasspath(ClasspathUtil.java:211)\n\tat org.eclipse.jdt.apt.core.internal.generatedfile.GeneratedSourceFolderManager.addToClasspath(GeneratedSourceFolderManager.java:132)\n\tat org.eclipse.jdt.apt.core.internal.generatedfile.GeneratedSourceFolderManager.ensureFolderExists(GeneratedSourceFolderManager.java:192)\n\tat org.eclipse.jdt.apt.core.internal.generatedfile.GeneratedSourceFolderManager.ensureFolderExists(GeneratedSourceFolderManager.java:226)\n\tat org.eclipse.jdt.apt.core.internal.generatedfile.GeneratedFileManager.compilationStarted(GeneratedFileManager.java:365)\n\tat org.eclipse.jdt.apt.core.internal.AptProject.compilationStarted(AptProject.java:66)\n\tat org.eclipse.jdt.apt.core.internal.AptCompilationParticipant.aboutToBuild(AptCompilationParticipant.java:262)\n\tat org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:652)\n\tat org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:185)\n\tat org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)\n\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)\n\tat org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)\n\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)\n\tat org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)\n\tat org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:594)\n\tat org.eclipse.core.internal.resources.Workspace.build(Workspace.java:483)\n\tat org.eclipse.jdt.ls.core.internal.handlers.BuildWorkspaceHandler.buildWorkspace(BuildWorkspaceHandler.java:65)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$28(JDTLanguageServer.java:1001)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$61(JDTLanguageServer.java:1236)\n\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)\n\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)\n"

[ERROR][2024-06-01 16:00:08] ...lsp/handlers.lua:623	"Jun 1, 2024, 4:00:08 PM Error occured while building workspace. Details: \n message: Project 'reprocessing-bordnet-service' is missing required Java project: 'reprocessing-map-client'; code: 964; resource: /home/boyanmihovski/Workspace/reprocessing/reprocessing-bordnet-service;\n message: The project cannot be built until build path errors are resolved; code: 0; resource: /home/boyanmihovski/Workspace/reprocessing/reprocessing-bordnet-service;\n message: The import com..reprocessing.common cannot be resolved; code: 268435846; resource: 

[build.gradle.txt](https://github.com/user-attachments/files/15521955/build.gradle.txt)

**Comment by imbacraft** [comment]
One more thing that might help is to always load the JDTLS autocmd at the end of the init.lua file. This way we make sure that there is no race for loading for plugins with ft = "java" lazyloading setup.

You can try this out on the "development" branch. I've implemented it there.

Also, what is the gradle version?

**Comment by bmihovski** [comment]
The update + recompile doesn't work due to the missing deps   ▷ 2    reprocessing-job-management/reprocessing-job-management-service/:1:1 Project 'reprocessing-job-management-service' is missing required Java project: 'reprocessing-map-client'

I tried the development changes however the issue is still remaining 

------------------------------------------------------------
Gradle 8.7
------------------------------------------------------------

Build time:   2024-03-22 15:52:46 UTC
Revision:     650af14d7653aa949fce5e886e685efc9cf97c10

Kotlin:       1.9.22
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.2 (Amazon.com Inc. 21.0.2+13-LTS)
OS:           Linux 5.15.0-87-generic amd64

**Comment by imbacraft** [comment]
Gradle && Java are compatible, including the JVM that gradle runs on. So if nothing here has helped, I think modifying the build.gradle file might be the only solution.

The project works on IntelliJ because it doesn't use m2e for building the project. The error should appear for neovim, vscode and eclipse only.

On how you should modify the build.gradle, I would take a look at [this comment](https://github.com/redhat-developer/vscode-java/issues/177#issuecomment-1133516429). The point is to explicitly instruct gradle to include the generated sources.

**Comment by bmihovski** [comment]
Thank you let see what will happen most likely they may not accept my pr with the changes because all of them are using idea :( 
I remember when it worked with dusk. Ironically, when we used nvim-java :) There is something which overcoming this issue

**Comment by imbacraft** [comment]
That's an issue to look into then. I will try to find what nvim-java does. One last thing you can try is this setting in jdtls.lua:

```lua
  local lsp_settings = {
    java = {
      autobuild = { enabled = false };
}

```

This will disable autobuild for the project. Then open your project, let jdtls initialize and the manually ask to compile with Space + j + C. Let's see what happens.

Hope the best for your PR.

**Comment by bmihovski** [comment]
@imbacraft I managed to fix it by replacing the jdtls.lua content with the example from here https://lsp-zero.netlify.app/v3.x/guide/setup-with-nvim-jdtls.html

It looks like the problem is with our implementation

**Comment by imbacraft** [comment]
Good find. I will go through it again then. One apparent difference is that it uses .git only as root marker. Maybe that was it?

**Comment by bmihovski** [comment]
Here is the direct comparison https://github.com/bmihovski/dusk.nvim/commit/8ff0ea677f751bcb7f3fc399c7d63292e5e596de

**Comment by bmihovski** [comment]
Also this is interesting
https://github.com/bmihovski/dusk.nvim/commit/8ff0ea677f751bcb7f3fc399c7d63292e5e596de#diff-ec794bb18823cae3bfccbcf202db6d7841d31aedc201ea8021521b5a4f28c480L212

**Comment by imbacraft** [comment]
Mostly are just renamings of variables for myself to make it more readable. Other than that, there are some enhancements like snippet support (which I consider essential). Anyway, I will refactor it to bring it closer to the original. Do you have a project with this error I can try it on?

**Comment by bmihovski** [comment]
The agent is Lombok this is very different than the other example

**Comment by imbacraft** [comment]
That's why I renamed the variable. If you check the original the agent is indeed lombok. I renamed it for clarity.

path.java_agent = jdtls_install .. '/lombok.jar'

**Comment by bmihovski** [comment]
Unfortunately it only present with the complex project at work It looks like it can be tested only from my side

**Comment by imbacraft** [comment]
On development branch I did some refactorings of the jdtls.lua. Kindly report if it works, thanks!

**Comment by bmihovski** [comment]
@imbacraft thanks for the changes. I found the exact the reason for the issue. As you predicted it was the root marker it should be .git or something else present in the main dir only. In my case the project contains multiple modules and each with it's own build.gradle 
https://github.com/bmihovski/dusk.nvim/commit/e62d38bee6f42dcea6cca8b37b6e219686a7f0b1#diff-ec794bb18823cae3bfccbcf202db6d7841d31aedc201ea8021521b5a4f28c480
In order to reproduce the problem the setup should be like that.

The next question is do we still need the changes from develop since they are not required anymore?

**Comment by bmihovski** [comment]
I spotted something about sonarlint and jdtls When I had the issue the sonarlint was loaded immediately after the root marker fix the sonar was load with a delay. When C++ and Python (no jdtls) is always loaded immediately.

**Comment by bmihovski** [comment]
last thing is we should disable lsp log file this file is expanding very rapidly and will cause us issues https://github.com/bmihovski/dusk.nvim/commit/e62d38bee6f42dcea6cca8b37b6e219686a7f0b1#diff-4a41a7c4ca468b3a3441ee8d6031aa463dd0285a267cdfed7d3f90e16ca93eccR73

**Comment by imbacraft** [comment]
Thanks for confirming that it was a root marker issue, because I was unable to spot anything else wrong with the config. I will keep the changes in the development branch, since they make it a bit cleaner. I like your change about the lsplogs also. Great input.

**Comment by imbacraft** [comment]
Letest commit on development cleans up jdtls.lua. I added some more configuration options also (like organize imports on save) for users to choose. LspLogs disabled. Will merge it on master soon.

**Comment by bmihovski** [comment]
Thanks for applying the marker fix. By the way it is worth it of having gradlew or mvnw as marker as well when some small projects are done in particular following online training or something where no git is required. The build.gradle and Pom.xml can be in any folder however the wrappers are only in the root directory

**Comment by imbacraft** [comment]
Done
